import { TranscriptChunk } from '../types';
import { saveTranscript, getTranscript } from '../utils/storage';

export interface TranscriptResult {
  success: boolean;
  chunks: TranscriptChunk[];
  language?: string;
  isAutoGenerated?: boolean;
  error?: string;
}

/**
 * Extracts the transcript for a YouTube video.
 * Checks local cache first, then fetches caption tracks from YouTube's player response.
 */
export async function extractTranscript(videoId: string): Promise<TranscriptResult> {
  if (!videoId) {
    return { success: false, chunks: [], error: 'Invalid video ID' };
  }

  // 1. Check local storage cache
  try {
    const cached = await getTranscript(videoId);
    if (cached && cached.length > 0) {
      console.log(`[Scribe Transcript] Loaded ${cached.length} chunks from cache for video ${videoId}`);
      return { success: true, chunks: cached };
    }
  } catch (err) {
    console.warn('[Scribe Transcript] Cache check failed:', err);
  }

  console.log(`[Scribe Transcript] Fetching transcript for video ${videoId}...`);

  // 2. Fetch page HTML to extract captionTracks
  try {
    const trackUrl = await findCaptionTrackUrl(videoId);
    if (trackUrl) {
      const chunks = await fetchAndParseTimedText(trackUrl);
      if (chunks && chunks.length > 0) {
        await saveTranscript(videoId, chunks);
        return { success: true, chunks };
      }
    }
  } catch (err) {
    console.warn('[Scribe Transcript] Failed fetching caption track via page HTML:', err);
  }

  // 3. Fallback: try timedtext direct endpoint for en
  try {
    const directUrl = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&fmt=json3`;
    const chunks = await fetchAndParseTimedText(directUrl);
    if (chunks && chunks.length > 0) {
      await saveTranscript(videoId, chunks);
      return { success: true, chunks };
    }
  } catch (err) {
    console.warn('[Scribe Transcript] Fallback direct timedtext failed:', err);
  }

  // 4. Fallback: try DOM transcript panel scraper if open
  try {
    const domChunks = scrapeTranscriptFromDOM();
    if (domChunks && domChunks.length > 0) {
      await saveTranscript(videoId, domChunks);
      return { success: true, chunks: domChunks };
    }
  } catch (err) {
    console.warn('[Scribe Transcript] DOM scraping fallback failed:', err);
  }

  return {
    success: false,
    chunks: [],
    error: 'No captions/transcript available for this video.',
  };
}

/**
 * Finds the timedtext caption URL from the YouTube watch page HTML
 */
async function findCaptionTrackUrl(videoId: string): Promise<string | null> {
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const res = await fetch(pageUrl, { credentials: 'omit' });
  const html = await res.text();

  // Search for playerCaptionsTracklistRenderer
  const match = html.match(/"captionTracks":\s*(\[.*?\])/s);
  if (!match || !match[1]) {
    // Check if captions are disabled or unavailable
    return null;
  }

  try {
    const tracks = JSON.parse(match[1]);
    if (!Array.isArray(tracks) || tracks.length === 0) return null;

    // Prefer English tracks, else first available track
    const enTrack =
      tracks.find((t: any) => t.languageCode === 'en' && t.kind !== 'asr') ||
      tracks.find((t: any) => t.languageCode?.startsWith('en')) ||
      tracks.find((t: any) => t.vssId?.includes('.en')) ||
      tracks[0];

    if (enTrack && enTrack.baseUrl) {
      let url = enTrack.baseUrl;
      if (!url.includes('fmt=')) {
        url += '&fmt=json3';
      }
      return url;
    }
  } catch (e) {
    console.warn('[Scribe Transcript] Error parsing captionTracks JSON:', e);
  }

  return null;
}

/**
 * Fetches and parses timedtext (handles JSON3 and XML formats)
 */
async function fetchAndParseTimedText(url: string): Promise<TranscriptChunk[]> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Timedtext HTTP error ${res.status}`);
  }

  const text = await res.text();

  // Check if JSON3
  if (text.trim().startsWith('{')) {
    return parseJson3Transcript(text);
  }

  // Otherwise XML
  return parseXmlTranscript(text);
}

function parseJson3Transcript(jsonText: string): TranscriptChunk[] {
  const data = JSON.parse(jsonText);
  if (!data.events || !Array.isArray(data.events)) {
    return [];
  }

  const chunks: TranscriptChunk[] = [];

  for (const event of data.events) {
    if (!event.segs || !Array.isArray(event.segs)) continue;

    const startMs = event.tStartMs || 0;
    const durMs = event.dDurationMs || 0;
    const fullText = event.segs
      .map((s: any) => s.utf8 || '')
      .join('')
      .replace(/[\n\r]+/g, ' ')
      .trim();

    if (fullText && fullText !== '\n') {
      chunks.push({
        start: +(startMs / 1000).toFixed(2),
        duration: +(durMs / 1000).toFixed(2),
        text: decodeHtmlEntities(fullText),
      });
    }
  }

  return mergeSmallChunks(chunks);
}

function parseXmlTranscript(xmlText: string): TranscriptChunk[] {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xmlText, 'text/xml');
  const textNodes = xmlDoc.getElementsByTagName('text');
  const chunks: TranscriptChunk[] = [];

  for (let i = 0; i < textNodes.length; i++) {
    const node = textNodes[i];
    const start = parseFloat(node.getAttribute('start') || '0');
    const dur = parseFloat(node.getAttribute('dur') || '0');
    const content = (node.textContent || '').replace(/[\n\r]+/g, ' ').trim();

    if (content) {
      chunks.push({
        start: +start.toFixed(2),
        duration: +dur.toFixed(2),
        text: decodeHtmlEntities(content),
      });
    }
  }

  return mergeSmallChunks(chunks);
}

function scrapeTranscriptFromDOM(): TranscriptChunk[] {
  const segments = document.querySelectorAll(
    'ytd-transcript-segment-renderer, ytd-transcript-body-renderer ytd-transcript-segment-renderer'
  );
  if (segments.length === 0) return [];

  const chunks: TranscriptChunk[] = [];

  segments.forEach((seg) => {
    const timeEl = seg.querySelector('.segment-timestamp, .yt-core-attributed-string');
    const textEl = seg.querySelector('.segment-text, yt-formatted-string.segment-text');

    const timeStr = timeEl ? (timeEl as HTMLElement).innerText.trim() : '00:00';
    const text = textEl ? (textEl as HTMLElement).innerText.trim() : '';

    if (text) {
      const parts = timeStr.split(':').map(Number);
      let start = 0;
      if (parts.length === 2) start = parts[0] * 60 + parts[1];
      if (parts.length === 3) start = parts[0] * 3600 + parts[1] * 60 + parts[2];

      chunks.push({
        start,
        duration: 3,
        text,
      });
    }
  });

  return mergeSmallChunks(chunks);
}

/**
 * Group or merge consecutive small sentence fragments into readable 10-30s chunks
 */
function mergeSmallChunks(chunks: TranscriptChunk[], minDuration: number = 6): TranscriptChunk[] {
  if (chunks.length <= 1) return chunks;

  const merged: TranscriptChunk[] = [];
  let current: TranscriptChunk = { ...chunks[0] };

  for (let i = 1; i < chunks.length; i++) {
    const next = chunks[i];
    const gap = next.start - (current.start + current.duration);

    // Merge if current chunk duration is under minDuration and gap isn't huge (< 4s)
    if (current.duration < minDuration && gap < 4 && current.text.length < 200) {
      current.duration = +(next.start + next.duration - current.start).toFixed(2);
      current.text = `${current.text} ${next.text}`.trim();
    } else {
      merged.push(current);
      current = { ...next };
    }
  }

  merged.push(current);
  return merged;
}

function decodeHtmlEntities(str: string): string {
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, dec) => String.fromCharCode(dec));
}
